INSERT INTO "users" ("username", "hashedPassword")
VALUES ('johndoe', 'Mysecretpassword1!');

INSERT INTO "recipes" ("name", "description", "photoUrl", "steps", "ingredients", "userId")
VALUES
('Chocolate Cake', 'A delicious chocolate cake recipe', 'https://www.hersheyland.com/content/dam/hersheyland/en-us/recipes/recipe-images/2_Hersheys_Perfectly_Chocolate_Cake_11-18.jpeg',
        '{"Preheat the oven to 350F","Mix dry ingredients","Mix wet ingredients","Combine dry and wet ingredients","Bake for 30 minutes"}',
        '{"Flour","Sugar","Cocoa powder","Eggs","Milk","Oil","Vanilla extract","Baking powder","Salt"}', 1),
('Spicy Chicken Tacos', 'These spicy chicken tacos are perfect for a quick and easy weeknight meal. The chicken is seasoned with a spicy blend of seasonings and then grilled to perfection. Serve with your favorite toppings!', 'https://www.pbs.org/food/wp-content/blogs.dir/2/files/2022/05/TonyChickenTacos.jpg', '{"Grill the chicken","Warm the tortillas","Assemble the tacos"}', '{"chicken breast","spices","tortillas","lettuce","tomatoes","sour cream","cheese","avocado"}', 1),
  ('Vegetarian Lasagna', 'This delicious vegetarian lasagna is packed with flavor and loaded with veggies. Layers of lasagna noodles, spinach, mushrooms, and a rich tomato sauce make this a crowd-pleasing favorite.', 'https://kristineskitchenblog.com/wp-content/uploads/2022/07/vegetable-lasagna-recipe-18.jpg', '{"Preheat oven","Prepare the lasagna noodles","Cook the vegetables","Assemble the lasagna","Bake in the oven"}', '{"lasagna noodles","spinach","mushrooms","tomato sauce","cheese"}', 1),
  ('Garlic Butter Shrimp', 'Garlic butter shrimp is a classic recipe that is quick, easy, and delicious. Serve over rice or with your favorite veggies for a satisfying meal!', 'https://www.thespruceeats.com/thmb/Kk9ncgxXYVWmD9MvHLAHOU4Zto4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/grilled-shrimp-with-garlic-butter-dipping-sauce-3060876-Hero_01-987656c360754fc79b6e09b83e0361b1.jpg', '{"Preheat the skillet","Melt the butter","Add the garlic and shrimp","Cook until shrimp are pink","Serve with rice or veggies"}', '{"shrimp","garlic","butter","rice","veggies"}', 1),
  ('Beef Stroganoff', 'Beef stroganoff is a classic dish that is sure to please. Tender strips of beef are simmered in a rich and creamy sauce, then served over egg noodles. Perfect for a cozy dinner at home!', 'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2Farchive%2Fe1ea1acf00ff5d98f8deed1b2c8223af59a5c09c', '{"Season the beef","Sear the beef","Cook the onions and mushrooms","Add the broth and sour cream","Serve over egg noodles"}', '{"beef strips","onions","mushrooms","beef broth","sour cream","egg noodles"}', 1),
  ('Mushroom Risotto', 'This mushroom risotto is a comforting and flavorful dish that is perfect for a cozy night in. Creamy risotto is studded with sautéed mushrooms and finished with a sprinkle of Parmesan cheese.', 'https://www.feastingathome.com/wp-content/uploads/2022/02/Mushroom-Risotto_-18.jpg', '{"Cook the mushrooms","Make the risotto","Add the mushrooms","Finish with Parmesan cheese"}', '{"risotto rice","mushrooms","onions","garlic","chicken broth","Parmesan cheese"}', 1),
  ('Baked Salmon', 'Baked salmon is a simple and healthy meal that is perfect for a quick dinner. Top with your favorite seasonings and serve with your favorite veggies!', 'https://assets.epicurious.com/photos/62d6c5146b6e74298a39d06a/16:9/w_4787,h_2692,c_limit/BakedSalmon_RECIPE_04142022_9780_final.jpg', '{"Preheat the oven","Season the salmon","Bake in the oven","Serve with veggies"}', '{"salmon fillets","lemon","herbs","olive oil","salt","pepper","veggies"}', 1)
